### ISSUE TITLE
Output not as desired

### ISSUE THREAD

**Issue by MBerger94** [URitzmann/ATM-code#1]
Here, then line https://github.com/URitzmann/ATM-code/blob/9420d28edb6b544d544ea2b80b4a6ce12a591d6b/main.c#L65 should be changed to `if (n % 100 == 0)`, then the if test when writing to mag.dat can be removed: https://github.com/URitzmann/ATM-code/blob/9420d28edb6b544d544ea2b80b4a6ce12a591d6b/main.c#L84 https://github.com/URitzmann/ATM-code/blob/9420d28edb6b544d544ea2b80b4a6ce12a591d6b/main.c#L88
Otherwise, results would be written to mag.dat every 1E5 time steps too.

**Comment by URitzmann** [comment]
You are completely right. It doesn't make sense this way. After going through all you comments, I will upload a new main-version and share it with the others.
