### ISSUE TITLE
Indexing

### ISSUE THREAD

**Issue by MBerger94** [URitzmann/ATM-code#3]
https://github.com/URitzmann/ATM-code/blob/9420d28edb6b544d544ea2b80b4a6ce12a591d6b/main.c#L77
Shouldn't the index be `mx += magx[k - RAND_PLUS]`? If so, then the two following lines need to be changed too.

**Comment by URitzmann** [comment]
And again, you are right!

**Comment by URitzmann** [comment]
Fixing that error also show that you have to change the order and normalize magx first and then sum it up to mx (and the other components)..
